# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envee < Formula
  desc "Per-directory environment variable manager"
  homepage "https://github.com/baken667/envee"
  version "0.1.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/baken667/envee/releases/download/v0.1.2/envee_0.1.2_darwin_amd64.tar.gz"
      sha256 "335289ad609b4a85663ea130471ed3d101037ac6326638d85501a78e98ad17bf"

      def install
        bin.install "envee"
        bin.install "enveed"
        bash_completion.install "completions/envee.bash" => "envee"
        zsh_completion.install "completions/envee.zsh" => "_envee"
        fish_completion.install "completions/envee.fish"
        man1.install Dir["manpages/*.1"]
      end
    end
    on_arm do
      url "https://github.com/baken667/envee/releases/download/v0.1.2/envee_0.1.2_darwin_arm64.tar.gz"
      sha256 "3ad546b52810c369c7f83692fb0c0e27313411450dcaed7e340985ab731d89c2"

      def install
        bin.install "envee"
        bin.install "enveed"
        bash_completion.install "completions/envee.bash" => "envee"
        zsh_completion.install "completions/envee.zsh" => "_envee"
        fish_completion.install "completions/envee.fish"
        man1.install Dir["manpages/*.1"]
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/baken667/envee/releases/download/v0.1.2/envee_0.1.2_linux_amd64.tar.gz"
        sha256 "6780e5f0d81fe88de6d4aef2f4a8f759d2f577c901200e8658352afffc96465a"

        def install
          bin.install "envee"
          bin.install "enveed"
          bash_completion.install "completions/envee.bash" => "envee"
          zsh_completion.install "completions/envee.zsh" => "_envee"
          fish_completion.install "completions/envee.fish"
          man1.install Dir["manpages/*.1"]
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/baken667/envee/releases/download/v0.1.2/envee_0.1.2_linux_arm64.tar.gz"
        sha256 "1bad0cce54d2efa409de3f78be4a180ad3770c81d1930bdf6e6248cc21d50638"

        def install
          bin.install "envee"
          bin.install "enveed"
          bash_completion.install "completions/envee.bash" => "envee"
          zsh_completion.install "completions/envee.zsh" => "_envee"
          fish_completion.install "completions/envee.fish"
          man1.install Dir["manpages/*.1"]
        end
      end
    end
  end

  def caveats
    <<~EOS
      To enable envee in your shell, add one of these to your config:
        bash:  eval "$(envee init bash)"
        zsh:   eval "$(envee init zsh)"
        fish:  envee init fish | source
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/envee --version")
    assert_match "_envee_hook", shell_output("#{bin}/envee init bash")
    assert_match "add-zsh-hook", shell_output("#{bin}/envee init zsh")
    assert_match "_envee_hook", shell_output("#{bin}/envee init fish")
  end
end
