# typed: true
# frozen_string_literal: true

# This formula is auto-generated by GoReleaser from baken/envee on every release.
# Do not edit by hand — submit changes to baken/envee/.goreleaser.yaml instead.
#
# See https://github.com/baken/envee and https://envee.dev for documentation.

class Envee < Formula
  desc "Per-directory environment variable manager (direnv replacement)"
  homepage "https://envee.dev"
  url "https://github.com/baken/envee/archive/refs/tags/v0.1.0.tar.gz"
  sha256 "REPLACE_AT_RELEASE"
  license "MIT"
  head "https://github.com/baken/envee.git", branch: "main"

  # envee is pure Go — no C dependencies. Build requires only Go.
  depends_on "go" => :build

  # Common dependencies for shell completions.
  # (No runtime deps; envee is a single static binary.)

  def install
    # Build flags mirror .goreleaser.yaml.
    ldflags = %W[
      -s -w
      -X github.com/baken/envee/internal/version.Version=#{version}
      -X github.com/baken/envee/internal/version.Commit=#{tap.git_head || "HEAD"}
      -X github.com/baken/envee/internal/version.Date=#{Time.now.utc.iso8601}
    ]

    system "go", "build", *std_go_args(ldflags: ldflags.join(" ")), "./cmd/envee"
    system "go", "build", *std_go_args(ldflags: ldflags.join(" "), output: bin/"enveed"), "./cmd/enveed"

    # Shell completions.
    bash_completion.install "completions/envee.bash" => "envee"
    zsh_completion.install "completions/envee.zsh" => "_envee"
    fish_completion.install "completions/envee.fish"

    # Man pages.
    man1.install Dir["manpages/*.1"]
  end

  test do
    # --version exits 0 and prints the version string.
    assert_match version.to_s, shell_output("#{bin}/envee --version")

    # `envee init bash` produces a shell hook that mentions _envee_hook.
    output = shell_output("#{bin}/envee init bash")
    assert_match "_envee_hook", output

    # `envee init zsh` produces a hook with `add-zsh-hook`.
    zsh_output = shell_output("#{bin}/envee init zsh")
    assert_match "add-zsh-hook", zsh_output
  end
end
