# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envee < Formula
  desc "Per-directory environment variable manager"
  homepage "https://github.com/baken667/envee"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/baken667/envee/releases/download/v0.3.0/envee_0.3.0_darwin_amd64.tar.gz"
      sha256 "686973e01b89eea9f68984628c903e63d0405fb7a593075339d472cff579181d"

      def install
        bin.install "envee"
        bin.install "enveed"
        bash_completion.install "completions/envee.bash" => "envee"
        zsh_completion.install "completions/envee.zsh" => "_envee"
        fish_completion.install "completions/envee.fish"
        man1.install Dir["manpages/*.1"]
      end
    end
    on_arm do
      url "https://github.com/baken667/envee/releases/download/v0.3.0/envee_0.3.0_darwin_arm64.tar.gz"
      sha256 "d4b589045aab067174c93deabb55b751c1e545daccdaa49244d269818758d652"

      def install
        bin.install "envee"
        bin.install "enveed"
        bash_completion.install "completions/envee.bash" => "envee"
        zsh_completion.install "completions/envee.zsh" => "_envee"
        fish_completion.install "completions/envee.fish"
        man1.install Dir["manpages/*.1"]
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/baken667/envee/releases/download/v0.3.0/envee_0.3.0_linux_amd64.tar.gz"
        sha256 "5c5ad151908cd7664e8fe9f86245f7dc400bb8212c0fb37703978e68a71e8fbe"

        def install
          bin.install "envee"
          bin.install "enveed"
          bash_completion.install "completions/envee.bash" => "envee"
          zsh_completion.install "completions/envee.zsh" => "_envee"
          fish_completion.install "completions/envee.fish"
          man1.install Dir["manpages/*.1"]
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/baken667/envee/releases/download/v0.3.0/envee_0.3.0_linux_arm64.tar.gz"
        sha256 "6e1ad70376aafc08cc2080c32e9092ebd63e11b8b9bbcaf29bfa147201a094c2"

        def install
          bin.install "envee"
          bin.install "enveed"
          bash_completion.install "completions/envee.bash" => "envee"
          zsh_completion.install "completions/envee.zsh" => "_envee"
          fish_completion.install "completions/envee.fish"
          man1.install Dir["manpages/*.1"]
        end
      end
    end
  end

  def caveats
    <<~EOS
      To enable envee in your shell, add one of these to your config:
        bash:  eval "$(envee init bash)"
        zsh:   eval "$(envee init zsh)"
        fish:  envee init fish | source
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/envee --version")
    assert_match "_envee_hook", shell_output("#{bin}/envee init bash")
    assert_match "add-zsh-hook", shell_output("#{bin}/envee init zsh")
    assert_match "_envee_hook", shell_output("#{bin}/envee init fish")
  end
end
